[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    # Biblioteca unificada da Adafruit para AHT10/AHT20
    adafruit/Adafruit AHTX0 @ ^2.0.5
    
    # Biblioteca SparkFun para o MAX30102
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    
    # Necessário para comunicação I2C estável
    adafruit/Adafruit BusIO @ ^1.14.1
    Wire