[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Define o sistema de arquivos para o LittleFS
board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit AHTX0 @ ^2.0.5
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    siara-cc/Sqlite3Esp32 @ ^2.5.0
    h2zero/NimBLE-Arduino @ ^1.4.1
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DI2C_BUFFER_LENGTH=128
    -Os          ; Otimizar por tamanho
    -ffunction-sections 
    -fdata-sections
